{
    'name': 'Shop Akademia 4',
    'version': '1.0',
    'summary': 'Shop Market summary',
    'description': 'Shop market description',
    'category': 'ak4',
    'author': 'Jeton',
    'website': 'Website',
    'depends': ['base'],
    'data': ['views/client_view.xml'],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
