{
    'name': 'Shop Akademia 4',
    'version': '1.0',
    'summary': 'Shop Market summary',
    'description': 'Shop market description',
    'category': 'ak4',
    'author': 'Jeton',
    'website': 'Website',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/invoice_sequence.xml',
        'views/client_view.xml',
        'views/employee_view.xml',
        'views/shop_product.xml',
        'views/shop_category.xml',
        'views/shop_invoice.xml',
        'report/invoice_report_view.xml',
        'report/invoice_product_report_view.xml',
        'wizard/invoice_report_wizard_view.xml',
        'wizard/invoice_product_report_wizard_view.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
