{
    'name': 'CP Shop',
    'version': '1.0',
    'summary': 'CP Shop Summery',
    'description': 'CP Shop Description',
    'category': 'Sales',
    'author': 'Jeton',
    'website': 'Website',
    'depends': ['base'],
    'data': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
